### ISSUE TITLE
Tidy up CSRF work

### ISSUE THREAD

**Issue by feedmypixel** [uktrade/data-hub-fe-beta2#87]
At the moment there is a [genCSRF](https://github.com/uktrade/data-hub-fe-beta2/blob/develop/src/lib/controller-utils.js#L122-L127) utility method that is called within a controller that [requires CSRF](https://github.com/uktrade/data-hub-fe-beta2/blob/8a37b17463faaea98023768bd350339a15c543e6/src/controllers/investment-start.controller.js#L14)

There is also the [csrf application level middleware](https://github.com/uktrade/data-hub-fe-beta2/blob/develop/src/server.js#L130) that is a middleware check placed on all routes within the application.

## Suggestion
Move these two things into one middleware that is then placed on routes that require csrf tokens. 
- We then don't run middleware on routes that don't require it
- Explicitly set the csrf requirement on the route rather than in the route handler method
- Have one place for csrf work

```
router.get('/investment/start', csrf, getHandler)
router.post('/investment/start', csrf, postHandler)
```

**Comment by ztolley** [comment]
They where in one middleware at one point but then we had some issues in forms that would use json lookup for things like advisor. Because of the way they worked it caused the token to be replaced, but the value in the form hadn't changed so it was using an invalid token.
